# @package ds
class: img_dataset
name: ours-cslab.test
input:
  - /data2/shaun/datasets/exposure_correction/exposure_errors/testing/INPUT_IMAGES/*
GT:
  - /data2/shaun/datasets/exposure_correction/exposure_errors/testing/expert_c_testing_set/*
